ip_address: "192.168.0.13"
ip_port: 10940
frame_id: "laser"

angle_min: -1.4
angle_max: 1.4
cluster: 1
skip: 0

calibrate_time: true
synchronize_time: true
time_offset: 0.0

error_limit: 4
error_reset_period: 5.0
